name: Sincronizar con GB Soluciones Digitales

on:
  push:
    branches:
      - main 

jobs:
  mirror_to_org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Mirror a la Organización
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: https://github.com/GB-Soluciones-Digitales/Ecommerce_Camel_Shop_Frontend.git
          user_name: Brian13b
          user_password: ${{ secrets.ORG_PAT }}
